apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: rkuuzl2y7-go 
  janus-idp.io/tekton: rkuuzl2y7-go
  backstage.io/kubernetes-id: rkuuzl2y7-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rkuuzl2y7-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml